### ISSUE TITLE
迷路の生成について

### ISSUE THREAD

**Issue by C0A21070** [327lyuya/ProjExD#14]
https://github.com/327lyuya/ProjExD/blob/74db48b685308dbf21eaa454ea0c3b1cd5e9d768/ex03/maze.py#L35
(30,20)にすると生成するマスの個数が多くなるため、描画できなくなると思う。また、マス一つずつのサイズを調整しないと画面に収まらないと思う。

**Comment by 327lyuya** [comment]
自分のPCでは全画面の表示ができないので勘弁してください。
マスのサイズはmaze_makerで変えています。
